//INTRODUCTION-------------------------------------------------------------------------------------------------------------------------------------------------
/*
This is the vex.h header file. For more information about header files, check the PDF. The vex.h header file is automatically generated by the VEX
extension. It contains the data types and other things necessary for the program to work. Typically, you would not change this file, but because I put
wheel_2r here, you only have to change the value of wheel_2r.
*/

//STRUCTURE EXPLANATION----------------------------------------------------------------------------------------------------------------------------------------
/*
The structure is automatically generated by the VEX extension and is not important for writing VEX software.
*/

//CODE---------------------------------------------------------------------------------------------------------------------------------------------------------

//Change this to the diameter of your robot's wheels.
#define wheel_2r 3.25

//DO NOT CHANGE THE FOLLOWING (AUTOMATICALLY GENERATED BY THE VEX EXTENSION)
#pragma once //This prevents the header file from being duplicated when included multiple times. For more information, refer to the PDF file. This should be supported
             //by any modern compiler.

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "v5.h"
#include "v5_vcs.h"

#define waitUntil(condition)                                                   \
  do {                                                                         \
    wait(5, msec);                                                             \
  } while (!(condition))

#define repeat(iterations)                                                     \
  for (int iterator = 0; iterator < iterations; iterator++)

//TROUBLESHOOTING----------------------------------------------------------------------------------------------------------------------------------------------
/*
Q: My problem is not in the troubleshooting section?
A: Go to the GitHub repository, click on the "Issues" tab, and submit a new issue describing your problem. I will respond.
*/
